### ISSUE TITLE
NoSuchWindowException at specific giveaway

### ISSUE THREAD

**Issue by SapuSeven** [TobiasPankner/Gleam-giveaway-bot#1]
After a couple hundred of giveaways, the bot crashes with the following error message:
```
Traceback (most recent call last):
  File "giveaway_bot.py", line 97, in <module>
    main()
  File "giveaway_bot.py", line 84, in main
    browser.refresh()
  File "/***/gleam-bot/src/browser.py", line 139, in refresh
    driver.refresh()
  File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 831, in refresh
    self.execute(Command.REFRESH)
  File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/***/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: headless chrome=83.0.4103.97)
```

This happens again when I restart the bot, always at the same giveaway.
If I wait a bit and restart the bot, it will complete new giveaways just fine, but crashes again at the same one after all new ones are finished.

I am running `Linux 5.4.36-1-MANJARO`.

**Comment by TobiasPankner** [comment]
Do you still have the link of the problematic giveaway and was this with the latest version?

**Comment by SapuSeven** [comment]
I am using an up-to-date clone of the repository.
The most recent problematic giveaway I encountered is https://playr.gg/giveaway/nxgAkf5.

**Comment by TobiasPankner** [comment]
I cannot reproduce the error, but in the newest version it might be fixed. Please try it again, if it didn't fix it you can change https://github.com/TobiasPankner/Gleam-giveaway-bot/blob/58a3cde68bc0c61f51ff7b306bc72d611b97eaed/giveaway_bot.py#L63
to `browser.init_driver(headless=False)`, this way you can see whats going on.

**Comment by SapuSeven** [comment]
Thank you for the suggestion, I'll try that.

**Comment by SapuSeven** [comment]
I can confirm that with your recent changes the bot managed to complete all giveaways without problems.
