### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by stickerx** [TobiasPankner/Gleam-giveaway-bot#13]
**1**
When I run `login.py`

Checking for win32 chromedriver:88.0.4324.96 in cache
Driver found in C:\Users\Meneow\.wdm\chromedriver\88.0.4324.96\win32/chromedriver.exe
Gleam login:
        Press any button when finished logging in

Do you want to complete playr.gg giveaways as well [y/n]?
y
Playrgg login:
        Press any button when finished logging in
Successfully saved authentication cookies
Press Enter or Esc to close console...

**2**   

When I run `giveaway_bot.py`

Traceback (most recent call last):
  File "C:\Users\Meneow\Desktop\Gleam-giveaway-bot-master\giveaway_bot.py", line 4, in <module>
    from src import browser, giveaway, logger, reddit, scraper, twitter, utils
  File "C:\Users\Meneow\Desktop\Gleam-giveaway-bot-master\src\giveaway.py", line 5, in <module>
    import colored
ModuleNotFoundError: No module named 'colored'

Press Enter or Esc to close console...

**Comment by TobiasPankner** [comment]
Did you install the requirements?

**Comment by stickerx** [comment]
![yooom](https://user-images.githubusercontent.com/41187653/107671220-81de1000-6c8b-11eb-8883-e7978181d3af.jpg)

after install requirements

**Comment by TobiasPankner** [comment]
Please try deleting this file: USER_HOME/.wdm/drivers.json. Then run it again

**Comment by stickerx** [comment]
![JJKKKKKKKKKKKKKKKKKK-11_193555](https://user-images.githubusercontent.com/41187653/107689162-6af5e880-6ca0-11eb-9abb-d02db1d5b1c8.jpg)

nothing, I did find any file with this name

**Comment by TobiasPankner** [comment]
Whats inside that folder?

**Comment by TobiasPankner** [comment]
Ans what OS are you using?

**Comment by stickerx** [comment]
![Uploading fffffffffffffffffff.jpg…]()

**Comment by stickerx** [comment]
![fffffffffffffffffff](https://user-images.githubusercontent.com/41187653/107689936-5bc36a80-6ca1-11eb-96ed-489627a96b42.jpg)

**Comment by stickerx** [comment]
win7 ultimate

**Comment by TobiasPankner** [comment]
Try deleting the chromedriver folder and rerun

**Comment by TobiasPankner** [comment]
If that doesn't work take a look at this: https://community.cryptomator.org/t/reg-is-not-recognized-as-an-internal-or-external-command/377

**Comment by stickerx** [comment]
Thank you so much sir I appreciate your effort with me 
![yooom](https://user-images.githubusercontent.com/41187653/107692547-de99f480-6ca4-11eb-89a2-5644aa16d01f.jpg)

**Comment by TobiasPankner** [comment]
You're welcome!
