### ISSUE TITLE
Having problem getting past "python login.py"

### ISSUE THREAD

**Issue by kuynh** [TobiasPankner/Gleam-giveaway-bot#14]
![image](https://user-images.githubusercontent.com/66544993/107744871-4f063d00-6cc8-11eb-9fed-aa1746148a9b.png)

Will provide any additional information needed.

**Comment by TobiasPankner** [comment]
It's an issue with your config file. You formatted it wrong, try putting the config file in a json parser online.

**Comment by kuynh** [comment]
Thank you, that was the issue.
