### ISSUE TITLE
Twitter_follow or twitter_tweet failing

### ISSUE THREAD

**Issue by Tracchy** [TobiasPankner/Gleam-giveaway-bot#15]
First I want to say thank you so much.  I've been struggling to learn python and this is the exact project I wanted to do!

I've run into an issue with twitter.  All my entries are red for twitter_follow and twitter_tweet and twitter_retweet.  Is there any log or clues to narrow down the issue?

I've done the following:
-Made a twitter account with dev keys and enabled RW.
-Re-generated keys
-Made a tweepy script to confirm read/write to twitter (worked).
-Deleted the project, resetup the config.json
-Re-generated keys
Same issue persist.

**Comment by TobiasPankner** [comment]
It's a problem with twitter detecting bot usage and restricting the API. Unfortunately I think this is not fixable.

**Comment by Tracchy** [comment]
> It's a problem with twitter detecting bot usage and restricting the API. Unfortunately I think this is not fixable.

Ah, good to know.  Thank you for the quick response and excellent work on this project.

**Comment by TobiasPankner** [comment]
Thank you! Glad to hear it's useful to you
