### ISSUE TITLE
Login.py - No entries on website

### ISSUE THREAD

**Issue by Tracchy** [TobiasPankner/Gleam-giveaway-bot#21]
Has anyone noticed that the login.py script loads the same page but the actual Gleam widget is missing on the right side?  Just wondering if there is an alternative way or if Gleam caught on and fixed this?

https://gleam.io/examples/competitions/every-entry-type

Is the URL.

**Comment by TobiasPankner** [comment]
It does this sometimes, just try refreshing, or going back once and then forward once in the browser.

**Comment by Tracchy** [comment]
Hi Tobias!

Thank you for taking the time to respond and help.  I hope you are doing well!

I tried your advice but still didn't see anything, but your input did lead me to the issue.  I have Ublock Origin installed as an add-in, even with it off I still couldn't see the entries.  HOWEVER!  When I disabled that adding, there it was showing like it use too.

Thank you for the help and the amazing application.
