### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by AshMan420** [TobiasPankner/Gleam-giveaway-bot#3]
When I run login.py, it closes in an instant. When I run it from cmd by using `py login.py`, it shows the error `json.decoder.JSONDecodeError: Invalid \escape: line 4 column 26 (char 60)`

**Comment by TobiasPankner** [comment]
There is an issue with your json file. Try putting it into a json parser website and see if there are errors.

**Comment by AshMan420** [comment]
I did, as you can see below. I even tried it on another computer thinking there was something wrong with the current one. But the same error showed up. You can see here what the issue is
![Annotation 2020-11-13 225456](https://user-images.githubusercontent.com/74422496/99101927-56537700-2603-11eb-9bc5-3cf2eae87791.png)

**Comment by TobiasPankner** [comment]
Try replacing the single backslashes (\\) with double backslashes (\\\\) or single slashes.

**Comment by AshMan420** [comment]
That seems to have worked, thanks! Now, I just have to sign in, and then run the `giveaway_bot.py`, right?

**Comment by TobiasPankner** [comment]
Yeah, run login.py, login and follow the instructions. After that run giveaway_bot.py.

**Comment by AshMan420** [comment]
I really appreciate your quick responses, it means a lot :)

**Comment by TobiasPankner** [comment]
You're welcome!

**Comment by AshMan420** [comment]
Also, if I receive an item I won from the bot, is it illegal? Like if I have an item ship to me or something?

**Comment by TobiasPankner** [comment]
I don't know, but usage of the bot is at your own risk.
