### ISSUE TITLE
Playr.gg Not Working

### ISSUE THREAD

**Issue by AshMan420** [TobiasPankner/Gleam-giveaway-bot#4]
The gleam part is working great (except the twitter stuff because I do not want to lie to get the API key), but as soon as it tries to do a playr.gg one, it runs into a bunch of errors, (the first one being related to\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py")

**Comment by TobiasPankner** [comment]
What are the errors and when does it occur?

**Comment by AshMan420** [comment]
I don't know how, but it randomly started working.

This is off topic, but could you tell me how I can add another giveaway website (vast.gg) to the code?

**Comment by TobiasPankner** [comment]
Okay good.
Vast.gg giveaways are just gleam giveaways, these should be found and completed automatically.

**Comment by AshMan420** [comment]
I just checked, and after running the program like 20 times, not a single one had been done. I guess it's too much work for such a small amount of giveaways, so I'll just complete them manually
