### ISSUE TITLE
the bot cant retweet?

### ISSUE THREAD

**Issue by dubgamer** [TobiasPankner/Gleam-giveaway-bot#7]
this might be a small problame and the bot is awsome, but the bot cant seem to be able to retweet. plus how do i remove the restriction for youtube subscrbing?

**Comment by TobiasPankner** [comment]
The problem with retweeting is with the twitter API look in the dashboard. What do you mean by restriction for youtube?

**Comment by dubgamer** [comment]
i checked the api and its should work, it has all the access it need and no
restrictions, anything specific i should look for in the api dashboard?
what i ment by that is that the bot is automatically ignoring some tasks
that it should be able to do, i.e subscribing to a youtube channel, is
there anyway to control what the bot is ignoring?
thank you for the quick response

‫בתאריך שבת, 19 בדצמ׳ 2020 ב-22:10 מאת ‪TobiasPankner‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by TobiasPankner** [comment]
Everything it ignores cannot be done automatically by the bot

**Comment by dubgamer** [comment]
Ok, thanks for the clarification.
Any tips on the retweet issue tho?

**Comment by TobiasPankner** [comment]
Your twitter account is somehow restricted, not an issue with the bot.
